### ISSUE TITLE
iOS Device Loading Issue

### ISSUE THREAD

**Issue by Redeye51** [stavroskasidis/BlazorWithIdentity#9]
I was looking at your project and one test was seeing what devices were supported. I know that Blazor supports iOS devices but in my testing, iPod Touch, iPhone, iPad and iPad Air, none of them would load your site. I've tested other Blazor sites on iOS devices without issues.  Is this a known issue that you've looked into?

Thank you for your time!
Bryan

**Comment by stavroskasidis** [comment]
I am not sure, since I don't own any apple devices myself. I will try to look into it.

The only thing I know is that in some versions safari had wasm disabled due to a security issue. But the latest version should be ok.

Also, while writing this response I just saw this issue at AspNetCore repo:
https://github.com/aspnet/AspNetCore/issues/12992

**Comment by stavroskasidis** [comment]
Also this:

https://github.com/mono/mono/issues/15989

**Comment by chucker** [comment]
>I was looking at your project and one test was seeing what devices were supported. I know that Blazor supports iOS devices but in my testing, iPod Touch, iPhone, iPad and iPad Air, none of them would load your site. I've tested other Blazor sites on iOS devices without issues. Is this a known issue that you've looked into?

If you're on an iOS 13 beta, this is tracked by https://github.com/mono/mono/issues/15588.

If you're on 12.x, that should work. Do you have a Mac so you can attach a Remote Web Inspector?

**Comment by stavroskasidis** [comment]
Closing this as external/not related with this repo
